version: '3.5'

services:
  django:
    build: .
    image: &app app
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    env_file: &envfile
      - ./env.env
    volumes:
      - .:/code
    depends_on:
      - broker
      - db

  worker:
    build: .
    image: *app
    restart: on-failure
    env_file: *envfile
    command: ["celery", "worker", "--app=scanvine", "--concurrency=1", "--hostname=worker@%h", "--loglevel=INFO"]
    volumes:
      - ./app:/app
    depends_on:
      - broker

  flower:
    image: zoomeranalytics/flower:0.9.1-4.0.2
    restart: on-failure
    env_file: *envfile
    ports:
      - "5555:5555"
    depends_on:
      - broker

  broker:
    image: rabbitmq
    restart: on-failure
    ports:
      - "5672:5672"

  db:
    image: postgres
    restart: on-failure
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=scanvine
      - POSTGRES_PASSWORD=grapevine
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
