version: '3.5'

services:
  web:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./server/nginx.conf.https:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./data/static:/static
    depends_on:
      - django
      - certbot
      - flower

  django:
    build: .
    image: &scanvine scanvine
    restart: unless-stopped
    env_file: .env
    command: gunicorn scanvine.wsgi:application --bind 0.0.0.0:8080
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    depends_on:
      - rabbitmq

  worker:
    build: .
    image: *scanvine
    restart: unless-stopped
    env_file: .env
    command: ["celery", "worker", "--app=scanvine", "--hostname=worker@%h", "--soft-time-limit=180", "--time-limit=7200", "--queues=fetch,internal", "--loglevel=INFO"]
    volumes:
      - .:/app
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    depends_on:
      - rabbitmq

  worker2:
    build: .
    image: *scanvine
    restart: unless-stopped
    env_file: .env
    command: ["celery", "worker", "--app=scanvine", "--hostname=worker@%h", "--soft-time-limit=180", "--time-limit=7200", "--queues=fetch,internal", "--loglevel=INFO"]
    volumes:
      - .:/app
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    depends_on:
      - rabbitmq

  worker3:
    build: .
    image: *scanvine
    restart: unless-stopped
    env_file: .env
    command: ["celery", "worker", "--app=scanvine", "--hostname=worker2@%h", "--soft-time-limit=180", "--time-limit=7200", "--queues=twitter,scoring,orchestrate", "--loglevel=INFO"]
    volumes:
      - .:/app
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    depends_on:
      - rabbitmq

  scheduler:
    build: .
    image: *scanvine
    restart: unless-stopped
    env_file: .env
    command: ["celery", "beat", "--app=scanvine", "--loglevel=INFO"]
    volumes:
      - .:/app
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    depends_on:
      - rabbitmq

  flower:
    image: mher/flower
    restart: unless-stopped
    command: ["flower", "--url-prefix=flower ", "--broker=amqp://guest:guest@rabbitmq:5672"]
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  