version: '3.5'

services:
  django:
    build: .
    image: &scanvine scanvine
    env_file: .env
    environment:
      - SCANVINE_ENV=production
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - POSTGRES_DB=postgres
      - POSTGRES_USER=scanvine
      - POSTGRES_PASSWORD=grapevine
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq

  worker:
    build: .
    image: *scanvine
    restart: on-failure
    env_file: .env
    environment:
      - SCANVINE_ENV=production
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - POSTGRES_DB=postgres
      - POSTGRES_USER=scanvine
      - POSTGRES_PASSWORD=grapevine
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    command: ["celery", "worker", "--app=scanvine", "--concurrency=1", "--hostname=worker@%h", "--loglevel=INFO", "--beat"]
    volumes:
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq

  flower:
    image: mher/flower
    restart: on-failure
    command: ["flower", "--broker=amqp://guest:guest@rabbitmq:5672"]
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq
    restart: on-failure
    ports:
      - "5672:5672"

  db:
    image: postgres
    restart: on-failure
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=scanvine
      - POSTGRES_PASSWORD=grapevine
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
