version: '3.5'

services:
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        #- /var/www/html/shared:/var/www/ # uncomment if running on Linux
        #- /etc/letsencrypt:/etc/letsencrypt #uncomment for production HTTPS
        #- /root/letsencrypt/lib:/var/lib/letsencrypt #uncomment for production HTTPS
    depends_on:
      - django

  django:
    build: .
    image: &scanvine scanvine
    env_file: .env
    environment:
      - SCANVINE_ENV=production
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - POSTGRES_DB=postgres
      - POSTGRES_USER=scanvine
      - POSTGRES_PASSWORD=grapevine
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - rabbitmq

  worker:
    build: .
    image: *scanvine
    restart: on-failure
    env_file: .env
    environment:
      - SCANVINE_ENV=production
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - POSTGRES_DB=postgres
      - POSTGRES_USER=scanvine
      - POSTGRES_PASSWORD=grapevine
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    command: ["celery", "worker", "--app=scanvine", "--concurrency=1", "--hostname=worker@%h", "--loglevel=INFO", "--beat"]
    volumes:
    volumes:
      - .:/app
    depends_on:
      - rabbitmq

  flower:
    image: mher/flower
    restart: on-failure
    command: ["flower", "--broker=amqp://guest:guest@rabbitmq:5672"]
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq
    restart: on-failure
    ports:
      - "5672:5672"
