apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels:
    app.kubernetes.io/instance: scanvine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: django
        image: python:3
        command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"        

---

apiVersion: v1
kind: Service
metadata:
  name: django
  annotations:
    dev.okteto.com/auto-ingress: "true"
  labels:
    app.kubernetes.io/instance: scanvine
spec:
  type: ClusterIP  
  ports:
  - name: django
    port: 8000
  selector:
    app: django
