# Generated by Django 3.0.5 on 2020-05-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200516_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='category',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='publication',
            name='average_credibility',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='publication',
            name='total_credibility',
            field=models.BigIntegerField(default=0),
        ),
    ]
