# Generated by Django 3.0.5 on 2020-05-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_article_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='initial_url',
            field=models.URLField(blank=True, max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(blank=True, db_index=True, max_length=1023),
        ),
        migrations.AlterField(
            model_name='share',
            name='url',
            field=models.URLField(max_length=1023),
        ),
    ]
