# Generated by Django 3.0.5 on 2020-05-25 22:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200521_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(db_index=True)),
                ('twitter_id', models.BigIntegerField(db_index=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(verbose_name=main.models.emptydict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='sharer',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=main.models.emptydict),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(db_index=True, max_length=511),
        ),
        migrations.AlterField(
            model_name='sharer',
            name='category',
            field=models.IntegerField(choices=[(-1, 'None'), (0, 'Health'), (1, 'Science'), (2, 'Tech'), (3, 'Business'), (4, 'Media')], db_index=True),
        ),
        migrations.AlterField(
            model_name='sharer',
            name='status',
            field=models.IntegerField(choices=[(2, 'Listed'), (1, 'Selected'), (0, 'Created'), (-1, 'Deselected'), (-2, 'Disabled'), (-3, 'Suggested'), (-4, 'Recommended')], db_index=True),
        ),
    ]
