# Generated by Django 3.0.5 on 2020-05-25 23:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200525_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=main.models.emptydict),
        ),
    ]
