# Generated by Django 3.0.5 on 2020-06-07 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0013_auto_20200527_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharer',
            name='protected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feedshare',
            name='share',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_shares', to='main.Share'),
        ),
        migrations.AlterField(
            model_name='feedshare',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_shares', to=settings.AUTH_USER_MODEL),
        ),
    ]
